// Generated by CoffeeScript 1.6.2
(function() {
  var init;

  init = function() {
    return $("#slider").slidesjs({
      width: 1480,
      height: 380,
      navigation: {
        active: false,
        effect: "fade"
      },
      pagination: {
        active: false,
        effect: "fade"
      },
      play: {
        auto: true,
        effect: "fade",
        interval: 5000
      },
      effect: {
        fade: {
          speed: 800
        }
      }
    });
  };

  $(document).on('ready', init);

  if ($(window).width() <= 768) {
    $("#main-nav > ul > li > a").attr("href", "#main-nav");
    $("#main-nav > ul > li > a").click(function() {
      if ($(this).hasClass("activo")) {
        return $(this).removeClass("activo");
      } else {
        $("#main-nav > ul > li > a").removeClass("activo");
        return $(this).addClass("activo");
      }
    });
  }

}).call(this);
